# -*- coding: utf-8 -*-
"""project1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/117EKNzTf4ZbFPSO25_H0c4pspx6t_1hH
"""

import pandas as pd
df = pd.read_csv('/content/city_temperature.csv', low_memory=False)
df = df[df['AvgTemperature'] != -99]
print("extracted columns \n")
print(f"{df[['Month', 'Year']].head()} \n")
yearly_avg = df.groupby('Year')['AvgTemperature'].mean()
monthly_avg = df.groupby('Month')['AvgTemperature'].mean()
threshold = 100
very_hot_days = df[df['AvgTemperature'] > threshold]
hot_days_count = len(very_hot_days)

print(f"The number of extremely hot days is over {threshold}: ")
print(f"there is {hot_days_count} in the database \n")

print("part of the hot days : \n")
print(f"{very_hot_days[['City', 'Country', 'Month', 'Day', 'Year', 'AvgTemperature']].head()} \n")

print("Average annual temperature : \n")
print(yearly_avg.head(), "\n")
print("Average monthly temperature : \n")
print(monthly_avg .head(), "\n")